# Generated by Django 6.0.6 on 2026-06-20 22:56

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='commission_text',
            field=wagtail.fields.RichTextField(blank=True, default='Request a custom painting from a travel photo, favourite street, house, facade, landscape, or meaningful place.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='commission_title',
            field=models.CharField(blank=True, default='Turn a place into a watercolour memory.', max_length=160),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_text',
            field=wagtail.fields.RichTextField(blank=True, default='A growing collection of travel sketches, architecture, landscapes, and process studies — each artwork with its own place, memory, and story.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_title',
            field=models.CharField(blank=True, default='A sketchbook of places.', max_length=160),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_eyebrow',
            field=models.CharField(blank=True, default='Watercolour painting & sketching', max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_highlight',
            field=models.CharField(blank=True, default='layers.', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_text',
            field=wagtail.fields.RichTextField(blank=True, default='Travel-inspired watercolour sketches by Johanna L — quiet streets, soft landscapes, architecture, and small moments captured through pencil, colour, and practice.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, default='Places, memories, and imperfect', max_length=160),
        ),
        migrations.AddField(
            model_name='homepage',
            name='process_text',
            field=wagtail.fields.RichTextField(blank=True, default='Watercolour is built in layers: light washes, pencil marks, small corrections, and the decision to keep going even when a piece is not perfect.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='process_title',
            field=models.CharField(blank=True, default='Soft layers, slow looking.', max_length=160),
        ),
    ]
