# Generated by Django 6.0.6 on 2026-06-20 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_type', models.CharField(choices=[('artwork', 'Ask about an artwork'), ('commission', 'Commission request'), ('general', 'General message')], default='general', max_length=30)),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(help_text="The visitor's message.")),
                ('budget', models.CharField(blank=True, help_text='Optional budget, useful for commissions.', max_length=120)),
                ('deadline', models.DateField(blank=True, help_text='Optional deadline for commission requests.', null=True)),
                ('reference_link', models.URLField(blank=True, help_text='Optional link to a reference photo, Instagram post, cloud folder, etc.')),
                ('status', models.CharField(choices=[('new', 'New'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artwork', models.ForeignKey(blank=True, help_text='Optional. Filled when someone asks about a specific artwork.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='artworks.artworkpage')),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
