# Generated by Django 6.0.6 on 2026-06-20 22:41

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Short introduction shown at the top of the gallery page.')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ArtworkPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('short_description', models.CharField(blank=True, help_text='One short sentence for gallery cards.', max_length=240)),
                ('story', wagtail.fields.RichTextField(blank=True, help_text='The memory, place, process, or story behind this artwork.')),
                ('category', models.CharField(choices=[('travel', 'Travel Sketches'), ('architecture', 'Architecture & Facades'), ('landscape', 'Landscapes'), ('sketchbook', 'Sketchbook Studies'), ('commission', 'Commission Examples')], default='travel', max_length=30)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('not_for_sale', 'Not for sale')], default='available', max_length=30)),
                ('place', models.CharField(blank=True, help_text='City/place/location, e.g. Kraków, Prague, Pollença.', max_length=120)),
                ('country', models.CharField(blank=True, help_text='Optional country, e.g. Poland, Czech Republic, Spain.', max_length=80)),
                ('medium', models.CharField(blank=True, default='Watercolour and pencil', max_length=120)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Leave empty if price should not be shown.', max_digits=8, null=True)),
                ('currency', models.CharField(default='€', max_length=8)),
                ('show_price', models.BooleanField(default=False, help_text='Turn on only if the price should be visible publicly.')),
                ('featured', models.BooleanField(default=False, help_text='Use later for homepage featured artworks.')),
                ('main_image', models.ForeignKey(help_text='Main image shown in the gallery and artwork detail page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ArtworkPageGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=240)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='artworks.artworkpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
